// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: paxos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaxosNode_SubmitTransaction_FullMethodName = "/paxos.PaxosNode/SubmitTransaction"
	PaxosNode_QueryBalance_FullMethodName      = "/paxos.PaxosNode/QueryBalance"
	PaxosNode_Prepare_FullMethodName           = "/paxos.PaxosNode/Prepare"
	PaxosNode_Accept_FullMethodName            = "/paxos.PaxosNode/Accept"
	PaxosNode_Commit_FullMethodName            = "/paxos.PaxosNode/Commit"
	PaxosNode_NewView_FullMethodName           = "/paxos.PaxosNode/NewView"
	PaxosNode_Checkpoint_FullMethodName        = "/paxos.PaxosNode/Checkpoint"
	PaxosNode_GetCheckpoint_FullMethodName     = "/paxos.PaxosNode/GetCheckpoint"
	PaxosNode_GetStatus_FullMethodName         = "/paxos.PaxosNode/GetStatus"
	PaxosNode_SetActive_FullMethodName         = "/paxos.PaxosNode/SetActive"
	PaxosNode_GetLogEntry_FullMethodName       = "/paxos.PaxosNode/GetLogEntry"
	PaxosNode_TwoPCPrepare_FullMethodName      = "/paxos.PaxosNode/TwoPCPrepare"
	PaxosNode_TwoPCCommit_FullMethodName       = "/paxos.PaxosNode/TwoPCCommit"
	PaxosNode_TwoPCAbort_FullMethodName        = "/paxos.PaxosNode/TwoPCAbort"
	PaxosNode_PrintBalance_FullMethodName      = "/paxos.PaxosNode/PrintBalance"
	PaxosNode_PrintDB_FullMethodName           = "/paxos.PaxosNode/PrintDB"
	PaxosNode_PrintView_FullMethodName         = "/paxos.PaxosNode/PrintView"
	PaxosNode_GetPerformance_FullMethodName    = "/paxos.PaxosNode/GetPerformance"
	PaxosNode_MigrationPrepare_FullMethodName  = "/paxos.PaxosNode/MigrationPrepare"
	PaxosNode_MigrationGetData_FullMethodName  = "/paxos.PaxosNode/MigrationGetData"
	PaxosNode_MigrationSetData_FullMethodName  = "/paxos.PaxosNode/MigrationSetData"
	PaxosNode_MigrationCommit_FullMethodName   = "/paxos.PaxosNode/MigrationCommit"
	PaxosNode_MigrationRollback_FullMethodName = "/paxos.PaxosNode/MigrationRollback"
	PaxosNode_GetAccessStats_FullMethodName    = "/paxos.PaxosNode/GetAccessStats"
	PaxosNode_TriggerRebalance_FullMethodName  = "/paxos.PaxosNode/TriggerRebalance"
	PaxosNode_PrintReshard_FullMethodName      = "/paxos.PaxosNode/PrintReshard"
	PaxosNode_FlushState_FullMethodName        = "/paxos.PaxosNode/FlushState"
)

// PaxosNodeClient is the client API for PaxosNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaxosNodeClient interface {
	// Client operations
	SubmitTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error)
	QueryBalance(ctx context.Context, in *BalanceQueryRequest, opts ...grpc.CallOption) (*BalanceQueryReply, error)
	// Paxos Phase 1: Leader Election
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PromiseReply, error)
	// Paxos Phase 2: Consensus
	Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptedReply, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReply, error)
	// Leader change
	NewView(ctx context.Context, in *NewViewRequest, opts ...grpc.CallOption) (*NewViewReply, error)
	// Checkpointing
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointReply, error)
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointReply, error)
	// Status and CLI
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	// Node control
	SetActive(ctx context.Context, in *SetActiveRequest, opts ...grpc.CallOption) (*SetActiveReply, error)
	// Recovery - request specific log entry from peers
	GetLogEntry(ctx context.Context, in *GetLogEntryRequest, opts ...grpc.CallOption) (*GetLogEntryReply, error)
	// Two-Phase Commit (2PC) for cross-shard transactions
	TwoPCPrepare(ctx context.Context, in *TwoPCPrepareRequest, opts ...grpc.CallOption) (*TwoPCPrepareReply, error)
	TwoPCCommit(ctx context.Context, in *TwoPCCommitRequest, opts ...grpc.CallOption) (*TwoPCCommitReply, error)
	TwoPCAbort(ctx context.Context, in *TwoPCAbortRequest, opts ...grpc.CallOption) (*TwoPCAbortReply, error)
	// Phase 7: Utility functions for debugging and monitoring
	PrintBalance(ctx context.Context, in *PrintBalanceRequest, opts ...grpc.CallOption) (*PrintBalanceReply, error)
	PrintDB(ctx context.Context, in *PrintDBRequest, opts ...grpc.CallOption) (*PrintDBReply, error)
	PrintView(ctx context.Context, in *PrintViewRequest, opts ...grpc.CallOption) (*PrintViewReply, error)
	GetPerformance(ctx context.Context, in *GetPerformanceRequest, opts ...grpc.CallOption) (*GetPerformanceReply, error)
	// Phase 9: Shard redistribution / data migration
	MigrationPrepare(ctx context.Context, in *MigrationPrepareRequest, opts ...grpc.CallOption) (*MigrationPrepareReply, error)
	MigrationGetData(ctx context.Context, in *MigrationGetDataRequest, opts ...grpc.CallOption) (*MigrationGetDataReply, error)
	MigrationSetData(ctx context.Context, in *MigrationSetDataRequest, opts ...grpc.CallOption) (*MigrationSetDataReply, error)
	MigrationCommit(ctx context.Context, in *MigrationCommitRequest, opts ...grpc.CallOption) (*MigrationCommitReply, error)
	MigrationRollback(ctx context.Context, in *MigrationRollbackRequest, opts ...grpc.CallOption) (*MigrationRollbackReply, error)
	GetAccessStats(ctx context.Context, in *GetAccessStatsRequest, opts ...grpc.CallOption) (*GetAccessStatsReply, error)
	TriggerRebalance(ctx context.Context, in *TriggerRebalanceRequest, opts ...grpc.CallOption) (*TriggerRebalanceReply, error)
	PrintReshard(ctx context.Context, in *PrintReshardRequest, opts ...grpc.CallOption) (*PrintReshardReply, error)
	// System control
	FlushState(ctx context.Context, in *FlushStateRequest, opts ...grpc.CallOption) (*FlushStateReply, error)
}

type paxosNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosNodeClient(cc grpc.ClientConnInterface) PaxosNodeClient {
	return &paxosNodeClient{cc}
}

func (c *paxosNodeClient) SubmitTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, PaxosNode_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) QueryBalance(ctx context.Context, in *BalanceQueryRequest, opts ...grpc.CallOption) (*BalanceQueryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceQueryReply)
	err := c.cc.Invoke(ctx, PaxosNode_QueryBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PromiseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromiseReply)
	err := c.cc.Invoke(ctx, PaxosNode_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptedReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptedReply)
	err := c.cc.Invoke(ctx, PaxosNode_Accept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitReply)
	err := c.cc.Invoke(ctx, PaxosNode_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) NewView(ctx context.Context, in *NewViewRequest, opts ...grpc.CallOption) (*NewViewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewViewReply)
	err := c.cc.Invoke(ctx, PaxosNode_NewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointReply)
	err := c.cc.Invoke(ctx, PaxosNode_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckpointReply)
	err := c.cc.Invoke(ctx, PaxosNode_GetCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, PaxosNode_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) SetActive(ctx context.Context, in *SetActiveRequest, opts ...grpc.CallOption) (*SetActiveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetActiveReply)
	err := c.cc.Invoke(ctx, PaxosNode_SetActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) GetLogEntry(ctx context.Context, in *GetLogEntryRequest, opts ...grpc.CallOption) (*GetLogEntryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogEntryReply)
	err := c.cc.Invoke(ctx, PaxosNode_GetLogEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) TwoPCPrepare(ctx context.Context, in *TwoPCPrepareRequest, opts ...grpc.CallOption) (*TwoPCPrepareReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwoPCPrepareReply)
	err := c.cc.Invoke(ctx, PaxosNode_TwoPCPrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) TwoPCCommit(ctx context.Context, in *TwoPCCommitRequest, opts ...grpc.CallOption) (*TwoPCCommitReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwoPCCommitReply)
	err := c.cc.Invoke(ctx, PaxosNode_TwoPCCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) TwoPCAbort(ctx context.Context, in *TwoPCAbortRequest, opts ...grpc.CallOption) (*TwoPCAbortReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwoPCAbortReply)
	err := c.cc.Invoke(ctx, PaxosNode_TwoPCAbort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) PrintBalance(ctx context.Context, in *PrintBalanceRequest, opts ...grpc.CallOption) (*PrintBalanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintBalanceReply)
	err := c.cc.Invoke(ctx, PaxosNode_PrintBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) PrintDB(ctx context.Context, in *PrintDBRequest, opts ...grpc.CallOption) (*PrintDBReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintDBReply)
	err := c.cc.Invoke(ctx, PaxosNode_PrintDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) PrintView(ctx context.Context, in *PrintViewRequest, opts ...grpc.CallOption) (*PrintViewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintViewReply)
	err := c.cc.Invoke(ctx, PaxosNode_PrintView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) GetPerformance(ctx context.Context, in *GetPerformanceRequest, opts ...grpc.CallOption) (*GetPerformanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPerformanceReply)
	err := c.cc.Invoke(ctx, PaxosNode_GetPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) MigrationPrepare(ctx context.Context, in *MigrationPrepareRequest, opts ...grpc.CallOption) (*MigrationPrepareReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationPrepareReply)
	err := c.cc.Invoke(ctx, PaxosNode_MigrationPrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) MigrationGetData(ctx context.Context, in *MigrationGetDataRequest, opts ...grpc.CallOption) (*MigrationGetDataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationGetDataReply)
	err := c.cc.Invoke(ctx, PaxosNode_MigrationGetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) MigrationSetData(ctx context.Context, in *MigrationSetDataRequest, opts ...grpc.CallOption) (*MigrationSetDataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationSetDataReply)
	err := c.cc.Invoke(ctx, PaxosNode_MigrationSetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) MigrationCommit(ctx context.Context, in *MigrationCommitRequest, opts ...grpc.CallOption) (*MigrationCommitReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationCommitReply)
	err := c.cc.Invoke(ctx, PaxosNode_MigrationCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) MigrationRollback(ctx context.Context, in *MigrationRollbackRequest, opts ...grpc.CallOption) (*MigrationRollbackReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationRollbackReply)
	err := c.cc.Invoke(ctx, PaxosNode_MigrationRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) GetAccessStats(ctx context.Context, in *GetAccessStatsRequest, opts ...grpc.CallOption) (*GetAccessStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccessStatsReply)
	err := c.cc.Invoke(ctx, PaxosNode_GetAccessStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) TriggerRebalance(ctx context.Context, in *TriggerRebalanceRequest, opts ...grpc.CallOption) (*TriggerRebalanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerRebalanceReply)
	err := c.cc.Invoke(ctx, PaxosNode_TriggerRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) PrintReshard(ctx context.Context, in *PrintReshardRequest, opts ...grpc.CallOption) (*PrintReshardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintReshardReply)
	err := c.cc.Invoke(ctx, PaxosNode_PrintReshard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) FlushState(ctx context.Context, in *FlushStateRequest, opts ...grpc.CallOption) (*FlushStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushStateReply)
	err := c.cc.Invoke(ctx, PaxosNode_FlushState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosNodeServer is the server API for PaxosNode service.
// All implementations must embed UnimplementedPaxosNodeServer
// for forward compatibility.
type PaxosNodeServer interface {
	// Client operations
	SubmitTransaction(context.Context, *TransactionRequest) (*TransactionReply, error)
	QueryBalance(context.Context, *BalanceQueryRequest) (*BalanceQueryReply, error)
	// Paxos Phase 1: Leader Election
	Prepare(context.Context, *PrepareRequest) (*PromiseReply, error)
	// Paxos Phase 2: Consensus
	Accept(context.Context, *AcceptRequest) (*AcceptedReply, error)
	Commit(context.Context, *CommitRequest) (*CommitReply, error)
	// Leader change
	NewView(context.Context, *NewViewRequest) (*NewViewReply, error)
	// Checkpointing
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointReply, error)
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointReply, error)
	// Status and CLI
	GetStatus(context.Context, *StatusRequest) (*StatusReply, error)
	// Node control
	SetActive(context.Context, *SetActiveRequest) (*SetActiveReply, error)
	// Recovery - request specific log entry from peers
	GetLogEntry(context.Context, *GetLogEntryRequest) (*GetLogEntryReply, error)
	// Two-Phase Commit (2PC) for cross-shard transactions
	TwoPCPrepare(context.Context, *TwoPCPrepareRequest) (*TwoPCPrepareReply, error)
	TwoPCCommit(context.Context, *TwoPCCommitRequest) (*TwoPCCommitReply, error)
	TwoPCAbort(context.Context, *TwoPCAbortRequest) (*TwoPCAbortReply, error)
	// Phase 7: Utility functions for debugging and monitoring
	PrintBalance(context.Context, *PrintBalanceRequest) (*PrintBalanceReply, error)
	PrintDB(context.Context, *PrintDBRequest) (*PrintDBReply, error)
	PrintView(context.Context, *PrintViewRequest) (*PrintViewReply, error)
	GetPerformance(context.Context, *GetPerformanceRequest) (*GetPerformanceReply, error)
	// Phase 9: Shard redistribution / data migration
	MigrationPrepare(context.Context, *MigrationPrepareRequest) (*MigrationPrepareReply, error)
	MigrationGetData(context.Context, *MigrationGetDataRequest) (*MigrationGetDataReply, error)
	MigrationSetData(context.Context, *MigrationSetDataRequest) (*MigrationSetDataReply, error)
	MigrationCommit(context.Context, *MigrationCommitRequest) (*MigrationCommitReply, error)
	MigrationRollback(context.Context, *MigrationRollbackRequest) (*MigrationRollbackReply, error)
	GetAccessStats(context.Context, *GetAccessStatsRequest) (*GetAccessStatsReply, error)
	TriggerRebalance(context.Context, *TriggerRebalanceRequest) (*TriggerRebalanceReply, error)
	PrintReshard(context.Context, *PrintReshardRequest) (*PrintReshardReply, error)
	// System control
	FlushState(context.Context, *FlushStateRequest) (*FlushStateReply, error)
	mustEmbedUnimplementedPaxosNodeServer()
}

// UnimplementedPaxosNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaxosNodeServer struct{}

func (UnimplementedPaxosNodeServer) SubmitTransaction(context.Context, *TransactionRequest) (*TransactionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedPaxosNodeServer) QueryBalance(context.Context, *BalanceQueryRequest) (*BalanceQueryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryBalance not implemented")
}
func (UnimplementedPaxosNodeServer) Prepare(context.Context, *PrepareRequest) (*PromiseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedPaxosNodeServer) Accept(context.Context, *AcceptRequest) (*AcceptedReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedPaxosNodeServer) Commit(context.Context, *CommitRequest) (*CommitReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedPaxosNodeServer) NewView(context.Context, *NewViewRequest) (*NewViewReply, error) {
	return nil, status.Error(codes.Unimplemented, "method NewView not implemented")
}
func (UnimplementedPaxosNodeServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedPaxosNodeServer) GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedPaxosNodeServer) GetStatus(context.Context, *StatusRequest) (*StatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPaxosNodeServer) SetActive(context.Context, *SetActiveRequest) (*SetActiveReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActive not implemented")
}
func (UnimplementedPaxosNodeServer) GetLogEntry(context.Context, *GetLogEntryRequest) (*GetLogEntryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogEntry not implemented")
}
func (UnimplementedPaxosNodeServer) TwoPCPrepare(context.Context, *TwoPCPrepareRequest) (*TwoPCPrepareReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TwoPCPrepare not implemented")
}
func (UnimplementedPaxosNodeServer) TwoPCCommit(context.Context, *TwoPCCommitRequest) (*TwoPCCommitReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TwoPCCommit not implemented")
}
func (UnimplementedPaxosNodeServer) TwoPCAbort(context.Context, *TwoPCAbortRequest) (*TwoPCAbortReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TwoPCAbort not implemented")
}
func (UnimplementedPaxosNodeServer) PrintBalance(context.Context, *PrintBalanceRequest) (*PrintBalanceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintBalance not implemented")
}
func (UnimplementedPaxosNodeServer) PrintDB(context.Context, *PrintDBRequest) (*PrintDBReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintDB not implemented")
}
func (UnimplementedPaxosNodeServer) PrintView(context.Context, *PrintViewRequest) (*PrintViewReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintView not implemented")
}
func (UnimplementedPaxosNodeServer) GetPerformance(context.Context, *GetPerformanceRequest) (*GetPerformanceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPerformance not implemented")
}
func (UnimplementedPaxosNodeServer) MigrationPrepare(context.Context, *MigrationPrepareRequest) (*MigrationPrepareReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationPrepare not implemented")
}
func (UnimplementedPaxosNodeServer) MigrationGetData(context.Context, *MigrationGetDataRequest) (*MigrationGetDataReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationGetData not implemented")
}
func (UnimplementedPaxosNodeServer) MigrationSetData(context.Context, *MigrationSetDataRequest) (*MigrationSetDataReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationSetData not implemented")
}
func (UnimplementedPaxosNodeServer) MigrationCommit(context.Context, *MigrationCommitRequest) (*MigrationCommitReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationCommit not implemented")
}
func (UnimplementedPaxosNodeServer) MigrationRollback(context.Context, *MigrationRollbackRequest) (*MigrationRollbackReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationRollback not implemented")
}
func (UnimplementedPaxosNodeServer) GetAccessStats(context.Context, *GetAccessStatsRequest) (*GetAccessStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccessStats not implemented")
}
func (UnimplementedPaxosNodeServer) TriggerRebalance(context.Context, *TriggerRebalanceRequest) (*TriggerRebalanceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerRebalance not implemented")
}
func (UnimplementedPaxosNodeServer) PrintReshard(context.Context, *PrintReshardRequest) (*PrintReshardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PrintReshard not implemented")
}
func (UnimplementedPaxosNodeServer) FlushState(context.Context, *FlushStateRequest) (*FlushStateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushState not implemented")
}
func (UnimplementedPaxosNodeServer) mustEmbedUnimplementedPaxosNodeServer() {}
func (UnimplementedPaxosNodeServer) testEmbeddedByValue()                   {}

// UnsafePaxosNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosNodeServer will
// result in compilation errors.
type UnsafePaxosNodeServer interface {
	mustEmbedUnimplementedPaxosNodeServer()
}

func RegisterPaxosNodeServer(s grpc.ServiceRegistrar, srv PaxosNodeServer) {
	// If the following call panics, it indicates UnimplementedPaxosNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaxosNode_ServiceDesc, srv)
}

func _PaxosNode_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).SubmitTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_QueryBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).QueryBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_QueryBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).QueryBalance(ctx, req.(*BalanceQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Accept(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_NewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).NewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_NewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).NewView(ctx, req.(*NewViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_GetCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_SetActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).SetActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_SetActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).SetActive(ctx, req.(*SetActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_GetLogEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).GetLogEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_GetLogEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).GetLogEntry(ctx, req.(*GetLogEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_TwoPCPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCPrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).TwoPCPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_TwoPCPrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).TwoPCPrepare(ctx, req.(*TwoPCPrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_TwoPCCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).TwoPCCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_TwoPCCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).TwoPCCommit(ctx, req.(*TwoPCCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_TwoPCAbort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCAbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).TwoPCAbort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_TwoPCAbort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).TwoPCAbort(ctx, req.(*TwoPCAbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_PrintBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).PrintBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_PrintBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).PrintBalance(ctx, req.(*PrintBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_PrintDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).PrintDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_PrintDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).PrintDB(ctx, req.(*PrintDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_PrintView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).PrintView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_PrintView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).PrintView(ctx, req.(*PrintViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_GetPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).GetPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_GetPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).GetPerformance(ctx, req.(*GetPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_MigrationPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationPrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).MigrationPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_MigrationPrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).MigrationPrepare(ctx, req.(*MigrationPrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_MigrationGetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationGetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).MigrationGetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_MigrationGetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).MigrationGetData(ctx, req.(*MigrationGetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_MigrationSetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationSetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).MigrationSetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_MigrationSetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).MigrationSetData(ctx, req.(*MigrationSetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_MigrationCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).MigrationCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_MigrationCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).MigrationCommit(ctx, req.(*MigrationCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_MigrationRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).MigrationRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_MigrationRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).MigrationRollback(ctx, req.(*MigrationRollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_GetAccessStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).GetAccessStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_GetAccessStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).GetAccessStats(ctx, req.(*GetAccessStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_TriggerRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).TriggerRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_TriggerRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).TriggerRebalance(ctx, req.(*TriggerRebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_PrintReshard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintReshardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).PrintReshard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_PrintReshard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).PrintReshard(ctx, req.(*PrintReshardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_FlushState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).FlushState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_FlushState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).FlushState(ctx, req.(*FlushStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaxosNode_ServiceDesc is the grpc.ServiceDesc for PaxosNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaxosNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.PaxosNode",
	HandlerType: (*PaxosNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _PaxosNode_SubmitTransaction_Handler,
		},
		{
			MethodName: "QueryBalance",
			Handler:    _PaxosNode_QueryBalance_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _PaxosNode_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _PaxosNode_Accept_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _PaxosNode_Commit_Handler,
		},
		{
			MethodName: "NewView",
			Handler:    _PaxosNode_NewView_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _PaxosNode_Checkpoint_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _PaxosNode_GetCheckpoint_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PaxosNode_GetStatus_Handler,
		},
		{
			MethodName: "SetActive",
			Handler:    _PaxosNode_SetActive_Handler,
		},
		{
			MethodName: "GetLogEntry",
			Handler:    _PaxosNode_GetLogEntry_Handler,
		},
		{
			MethodName: "TwoPCPrepare",
			Handler:    _PaxosNode_TwoPCPrepare_Handler,
		},
		{
			MethodName: "TwoPCCommit",
			Handler:    _PaxosNode_TwoPCCommit_Handler,
		},
		{
			MethodName: "TwoPCAbort",
			Handler:    _PaxosNode_TwoPCAbort_Handler,
		},
		{
			MethodName: "PrintBalance",
			Handler:    _PaxosNode_PrintBalance_Handler,
		},
		{
			MethodName: "PrintDB",
			Handler:    _PaxosNode_PrintDB_Handler,
		},
		{
			MethodName: "PrintView",
			Handler:    _PaxosNode_PrintView_Handler,
		},
		{
			MethodName: "GetPerformance",
			Handler:    _PaxosNode_GetPerformance_Handler,
		},
		{
			MethodName: "MigrationPrepare",
			Handler:    _PaxosNode_MigrationPrepare_Handler,
		},
		{
			MethodName: "MigrationGetData",
			Handler:    _PaxosNode_MigrationGetData_Handler,
		},
		{
			MethodName: "MigrationSetData",
			Handler:    _PaxosNode_MigrationSetData_Handler,
		},
		{
			MethodName: "MigrationCommit",
			Handler:    _PaxosNode_MigrationCommit_Handler,
		},
		{
			MethodName: "MigrationRollback",
			Handler:    _PaxosNode_MigrationRollback_Handler,
		},
		{
			MethodName: "GetAccessStats",
			Handler:    _PaxosNode_GetAccessStats_Handler,
		},
		{
			MethodName: "TriggerRebalance",
			Handler:    _PaxosNode_TriggerRebalance_Handler,
		},
		{
			MethodName: "PrintReshard",
			Handler:    _PaxosNode_PrintReshard_Handler,
		},
		{
			MethodName: "FlushState",
			Handler:    _PaxosNode_FlushState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxos.proto",
}
