// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/paxos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaxosNode_SubmitTransaction_FullMethodName = "/paxos.PaxosNode/SubmitTransaction"
	PaxosNode_Prepare_FullMethodName           = "/paxos.PaxosNode/Prepare"
	PaxosNode_Accept_FullMethodName            = "/paxos.PaxosNode/Accept"
	PaxosNode_Commit_FullMethodName            = "/paxos.PaxosNode/Commit"
	PaxosNode_NewView_FullMethodName           = "/paxos.PaxosNode/NewView"
	PaxosNode_Checkpoint_FullMethodName        = "/paxos.PaxosNode/Checkpoint"
	PaxosNode_GetCheckpoint_FullMethodName     = "/paxos.PaxosNode/GetCheckpoint"
	PaxosNode_GetStatus_FullMethodName         = "/paxos.PaxosNode/GetStatus"
)

// PaxosNodeClient is the client API for PaxosNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaxosNodeClient interface {
	// Client operations
	SubmitTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error)
	// Paxos Phase 1: Leader Election
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PromiseReply, error)
	// Paxos Phase 2: Consensus
	Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptedReply, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReply, error)
	// Leader change
	NewView(ctx context.Context, in *NewViewRequest, opts ...grpc.CallOption) (*NewViewReply, error)
	// Checkpointing
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointReply, error)
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointReply, error)
	// Status and CLI
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type paxosNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewPaxosNodeClient(cc grpc.ClientConnInterface) PaxosNodeClient {
	return &paxosNodeClient{cc}
}

func (c *paxosNodeClient) SubmitTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, PaxosNode_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PromiseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromiseReply)
	err := c.cc.Invoke(ctx, PaxosNode_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptedReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptedReply)
	err := c.cc.Invoke(ctx, PaxosNode_Accept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitReply)
	err := c.cc.Invoke(ctx, PaxosNode_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) NewView(ctx context.Context, in *NewViewRequest, opts ...grpc.CallOption) (*NewViewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewViewReply)
	err := c.cc.Invoke(ctx, PaxosNode_NewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointReply)
	err := c.cc.Invoke(ctx, PaxosNode_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckpointReply)
	err := c.cc.Invoke(ctx, PaxosNode_GetCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paxosNodeClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, PaxosNode_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaxosNodeServer is the server API for PaxosNode service.
// All implementations must embed UnimplementedPaxosNodeServer
// for forward compatibility.
type PaxosNodeServer interface {
	// Client operations
	SubmitTransaction(context.Context, *TransactionRequest) (*TransactionReply, error)
	// Paxos Phase 1: Leader Election
	Prepare(context.Context, *PrepareRequest) (*PromiseReply, error)
	// Paxos Phase 2: Consensus
	Accept(context.Context, *AcceptRequest) (*AcceptedReply, error)
	Commit(context.Context, *CommitRequest) (*CommitReply, error)
	// Leader change
	NewView(context.Context, *NewViewRequest) (*NewViewReply, error)
	// Checkpointing
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointReply, error)
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointReply, error)
	// Status and CLI
	GetStatus(context.Context, *StatusRequest) (*StatusReply, error)
	mustEmbedUnimplementedPaxosNodeServer()
}

// UnimplementedPaxosNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaxosNodeServer struct{}

func (UnimplementedPaxosNodeServer) SubmitTransaction(context.Context, *TransactionRequest) (*TransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedPaxosNodeServer) Prepare(context.Context, *PrepareRequest) (*PromiseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedPaxosNodeServer) Accept(context.Context, *AcceptRequest) (*AcceptedReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedPaxosNodeServer) Commit(context.Context, *CommitRequest) (*CommitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedPaxosNodeServer) NewView(context.Context, *NewViewRequest) (*NewViewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewView not implemented")
}
func (UnimplementedPaxosNodeServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedPaxosNodeServer) GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedPaxosNodeServer) GetStatus(context.Context, *StatusRequest) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPaxosNodeServer) mustEmbedUnimplementedPaxosNodeServer() {}
func (UnimplementedPaxosNodeServer) testEmbeddedByValue()                   {}

// UnsafePaxosNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaxosNodeServer will
// result in compilation errors.
type UnsafePaxosNodeServer interface {
	mustEmbedUnimplementedPaxosNodeServer()
}

func RegisterPaxosNodeServer(s grpc.ServiceRegistrar, srv PaxosNodeServer) {
	// If the following call pancis, it indicates UnimplementedPaxosNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaxosNode_ServiceDesc, srv)
}

func _PaxosNode_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).SubmitTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Accept(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_NewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).NewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_NewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).NewView(ctx, req.(*NewViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_GetCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaxosNode_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaxosNodeServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaxosNode_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaxosNodeServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaxosNode_ServiceDesc is the grpc.ServiceDesc for PaxosNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaxosNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.PaxosNode",
	HandlerType: (*PaxosNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _PaxosNode_SubmitTransaction_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _PaxosNode_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _PaxosNode_Accept_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _PaxosNode_Commit_Handler,
		},
		{
			MethodName: "NewView",
			Handler:    _PaxosNode_NewView_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _PaxosNode_Checkpoint_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _PaxosNode_GetCheckpoint_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PaxosNode_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paxos.proto",
}
